### ISSUE TITLE
useHead is not defined

### ISSUE THREAD

**Issue by zenonux** [johannschopplich/nuxt-gtag#12]
### Environment

nuxt 3.3.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xldqew?file=nuxt.config.ts

### Describe the bug

not work, show `useHead is not defined` error

**Comment by johannschopplich** [comment]
✅  Fixed in [v0.5.3](https://github.com/johannschopplich/nuxt-gtag/releases/tag/v0.5.3).
