### ISSUE TITLE
question: Does it support google tag manager?

### ISSUE THREAD

**Issue by zenonux** [johannschopplich/nuxt-gtag#13]
### Describe the feature

Does it support google tag manager?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
Not at the moment. I will probably create another module at some point with additional Google Tag Manager support.

**Comment by M-GRV** [comment]
I think it would be pretty helpful and insanely useful. Thanks!
