### ISSUE TITLE
[nuxt] error caught during app initialization ReferenceError: useHead is not defined

### ISSUE THREAD

**Issue by kennedyngigi4** [johannschopplich/nuxt-gtag#16]
I am getting this error on my Nuxt3 platform:

[nuxt] error caught during app initialization Refer
![Screenshot 2023-05-13 at 12 27 28 PM](https://github.com/johannschopplich/nuxt-gtag/assets/36414555/7703c369-67a2-42a0-9d7b-ae76abe51f3b)
enceError: useHead is not defined

**Comment by johannschopplich** [comment]
Please provide a minimum reproduction. Thanks in advance!

**Comment by johannschopplich** [comment]
Each `useHead` composable is imported from `#imports`. Thus, I can't reproduce the issue. If it persists, please provide a reproduction. Thanks!
