### ISSUE TITLE
Option to exclude route(s)?

### ISSUE THREAD

**Issue by jimmiejackson** [johannschopplich/nuxt-gtag#17]
### Describe the feature

I'm looking to implement GTag and am running in to issues getting vue-gtag to exclude routes (even though they supposedly have the option).

Does this library offer that sort of functionality? I'm personally only needing to exclude one single route, however I'm sure the ability to exclude wildcard paths (e.g. /blog/*) would also be helpful to others.

Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [x] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
Unfortunately, `vue-gtag` uses a different approach for excluded routes to work. 

This Nuxt module just injects the official Gtag.js and relies on its enhanced measurement feature to allow GA4 to automatically track page views in your Single Page Application. In comparison, `vue-gtag` manually watches for route changes and sends a `page_view` event via Gtag.

For route exclusion to work, we would have to implement a new method which as well uses the Vue Router to listen to route changes and send events manually.

**Comment by breizhwave** [comment]
or use the tag with non automatic page view :) check out my precedent issue https://github.com/johannschopplich/nuxt-gtag/issues/18
