### ISSUE TITLE
no data collected

### ISSUE THREAD

**Issue by breizhwave** [johannschopplich/nuxt-gtag#18]
### Environment

{
"private": true,
"scripts": {
"build": "nuxt build",
"dev": "nuxt dev",
"generate": "nuxt generate",
"preview": "nuxt preview",
"postinstall": "nuxt prepare"
},
"devDependencies": {
"nuxt": "^3.2.3",
"primeflex": "3.2.1",
"primeicons": "5.0.0",
"primevue": "^3.25.0"
},
"dependencies": {
"@pinia/nuxt": "^0.4.4",
"bootstrap": "^5.2.3",
"mixpanel-browser": "^2.47.0",
"nuxt-gtag": "^0.5.7",
"sass": "^1.56.1"
}
}

### Reproduction

used both yarn and pnpm and yarn do to add nuxt-gtag, front renders the gtag configuration, but does not add page view script. tried to add view script manually but still no change within analytics, no data collected, source here https://calculatrices-klosup-lrm.fr/calculatrices-2023/cloture-horizontale-simple/

window.NUXT={serverRendered:false,config:{public:{gtag:{id:"G-QxxxxxxxY",config:{},initialConsent:true,loadingStrategy:"defer"}}

### Describe the bug

not collecting data at all (similar to https://github.com/johannschopplich/nuxt-gtag/issues/11, except won't collect on other pages)

**Comment by breizhwave** [comment]
just needed to add page view event 

  gtag('event', 'page_view', {
      page_location: window.location.href,
      page_path: useRoute().path,
      page_title: document.title,
    })

**Comment by johannschopplich** [comment]
Have you ensured, that the Enhanced measurement feature is enabled to allow GA4 to automatically track page views in your Single Page Application?

To enable this feature, go to your Google Analytics 4 account, then navigate to "Admin" > "Data Streams" > "Web" > "Enhanced measurement settings." In this section, make sure the "Page views" toggle is enabled. Enabling the "Page views" toggle allows GA4 to track page changes based on browser history events in your Single Page Application.

**Comment by breizhwave** [comment]
thks did not know. I actually prefer to use the code because i'm on  SSG and not couting everything

**Comment by breizhwave** [comment]
thks anyway clsing

**Comment by johannschopplich** [comment]
Glad to hear you found a solution. 🙂

**Comment by notflip** [comment]
> just needed to add page view event
> 
> ```ts
> gtag('event', 'page_view', {
>   page_location: window.location.href,
>   page_path: useRoute().path,
>   page_title: document.title,
> })
> ```

Do we need to add this page_view event if the advanced tracking is enabled? Or only if it's not?

**Comment by johannschopplich** [comment]
You need this only if you have advanced tracking _disabled_.
