### ISSUE TITLE
useGtagConsent(true) isn't adding the gtag script to the head

### ISSUE THREAD

**Issue by chester-af** [johannschopplich/nuxt-gtag#19]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.9.0`
- Nuxt Version:     `3.5.2`
- Nitro Version:    `2.4.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `postcss`, `runtimeConfig`, `components`, `modules`, `gtag`, `lazyLoad`, `swiper`, `app`, `devServer`, `vite`, `ssr`
- Runtime Modules:  `@pinia/nuxt@0.4.11`, `nuxt-swiper@1.1.0`, `@vue-macros/nuxt@1.3.11`, `nuxt-lazy-load@3.0.4`, `nuxt-gtag@0.5.7`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vihbux?file=app.vue

### Describe the bug

Hello,

When I use the useGtagConsent() function and set it to true after clicking a button, it does not insert the script into the head which means that events aren't sent to Google Analytics. if you place the useGtagConsent(true) in onMounted of the component, it will insert the script into the head though but I only want to insert the script if the user clicks an accept button.

**Comment by hajiskyy** [comment]
Doesn't look like you have it installed it yet on that reproduction link. you might want to check it again properly

**Comment by johannschopplich** [comment]
This feature has been added in the latest release of Nuxt Gtag! You can now omit the `id` in your Nuxt Gtag module options and use `useGtagConsent` to pass a custom Gtag ID. If Gtag hasn't been initialized yet, it will be.
