### ISSUE TITLE
Setting the GTAG ID Dynamically

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [johannschopplich/nuxt-gtag#22]
### Describe the feature

We were wondering if its possible to set the GTAG ID Dynamically. 

We basically have a white label website where every domain that points towards the server has different layout and content.

Really hope this is possible :)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by ILLuMiNaTe7** [comment]
So basically the way we have programmed our website is that we have a initial server init upon loading the page. This loads the template and some other necessary data.We hope that during this initialization we can set the gtag id of the plugin. So it allows us to use multiple domains for the same project.For example something like this:const config = useRuntimeConfig()config.gtag.id = 'GT4313'However as of right now this of course is not possible.On Aug 14, 2023 16:31, Johann Schopplich ***@***.***> wrote:

We were wondering if its possible to set the GTAG ID Dynamically.

What do you mean by that? At runtime instead of build time? You can adapt the GTAG ID based on the NUXT_PUBLIC_GTAG_ID variable:
# Sets the `gtag.id` module option
NUXT_PUBLIC_GTAG_ID=G-XXXXXXXXXX

**Comment by johannschopplich** [comment]
Hey there, I've implemented an optional ID parameter for `useGtagConsent`: https://github.com/johannschopplich/nuxt-gtag/commit/7859fe6ecd9285723384887ef6b0b455723856e0

Make sure to set `initialConsent` to `false` in the module options. Then, you can fetch your data and initialize a specific Gtag ID:

```ts
useGtagConsent(true, { id: "XXX" })
```

Since no Gtag instance has been initialized until that point, it will do so for the custom ID. Hope that helps!

**Comment by ILLuMiNaTe7** [comment]
Hi @johannschopplich ,

I've tested the implementation however I'm encountering a weird issue that may be related to #19 .

For some reason, the script doesn't get injected into the head with your instructions. The only time it gets injected is when I do set the ID in the Nuxt config. However, then it also injects it 2 times. One time with the Nuxt config and another time with the new implementation.

As a result, the first collection for analytics also uses injection originating from Nuxt config. (G-XXXXXXX)
```
<script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX&amp;l=dataLayer&amp;cx=c"></script>
<script src="https://www.googletagmanager.com/gtag/js?id=G-4DJ1K7LHXI"></script>
```

This is my implementation:
Nuxt Config:
```
export default defineNuxtConfig({
  ...
  modules: [
    ...
    'nuxt-gtag'
  ],
  gtag: {
    initialConsent: false
    // id: 'G-XXXXXXXXXX' <<< If this is added it does work except for the first collection.
  }
  ...
})
```
Plugin:
```
export default defineNuxtPlugin(async () => {
   // Do some magic to get the GTAG ID:
   useGtagConsent(true, { id: 'G-4MJ1K7LSXM' })
})
```

**Comment by ILLuMiNaTe7** [comment]
Thanks for the quick handling. After testing the code it seems you have accidentally removed the import of defineNuxtPlugin.

This causes the following error:
```
Uncaught ReferenceError: defineNuxtPlugin is not defined
    at plugin.client.mjs?v=2faffd2d:1:1
```

Thanks for fixing this :)
