### ISSUE TITLE
Types for public runtime config

### ISSUE THREAD

**Issue by nandi95** [johannschopplich/nuxt-gtag#23]
### Environment

- Nuxt Version:     3.6.5

### Reproduction

use the package in a typescript setting.

### Describe the bug

there are some values set on the public config that haven't been typed. Here specifically:
https://github.com/johannschopplich/nuxt-gtag/blob/a51aacbe4019078c464cf17180a3af5d8246cd16/src/module.ts#L64

it would be helpful if this was typed somehow. Is there a way to do this with nuxt type generation? if not, maybe module augmentation?

**Comment by johannschopplich** [comment]
Hi there!

Nuxt tries to automatically generate a typescript interface from provided runtime config using [unjs/untyped](https://github.com/unjs/untyped). Although it is possible to manually type runtime configs, it shouldn't be needed in this case.

Once the plugin is added to the `modules` Nuxt config property, you should see the types:

<img width="848" alt="Bildschirmfoto 2023-08-19 um 11 35 46" src="https://github.com/johannschopplich/nuxt-gtag/assets/27850750/c4399025-44b6-4950-9972-3ce29e121aa2">
