### ISSUE TITLE
useTrackEvent typing improvement

### ISSUE THREAD

**Issue by nandi95** [johannschopplich/nuxt-gtag#28]
### Describe the feature

useTrackEvent doesn't have the same typing as the `useGtag()('event', ....nicely typed args)`

I tried to implement this but didn't get far with it. Not easy when I only have the GTag type to work with.
```ts
import type { Gtag } from '../types'
import { useGtag } from './useGtag'

type Event = Gtag | ((command: 'event') => never)
type OmitCommandParameter<T> = T extends (command: 'event', ...rest: infer R) => void ? (...args: R) => void : never

export function useTrackEvent(
  eventName: Parameters<OmitCommandParameter<Event>>[0],
  eventParams?: Parameters<OmitCommandParameter<Event>>[1],
) {
  const { gtag } = useGtag()
  gtag('event', eventName, eventParams)
}

```
Perhaps other types can be exported too?
It would make sense in case someone constructs the arguments outside of a function call.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
Valid point! Thanks for the hint and verbose issue description. 🙂
