### ISSUE TITLE
Browser Console Error: Uncaught ReferenceError: defineNuxtPlugin is not defined

### ISSUE THREAD

**Issue by modbender** [johannschopplich/nuxt-gtag#3]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction
```js
export default defineNuxtConfig({
  modules: ['nuxt-gtag'],

  gtag: {
    id: 'G-XXXXXXXXXX'
  }
})
```
### Describe the bug

GTag doesn't work. On browser console I see this error:

Uncaught ReferenceError: defineNuxtPlugin is not defined
    at plugin.client.mjs?v=54cefaf0:1:1

You should probably add this to plugin.client.ts

```js
import { defineNuxtPlugin, useRuntimeConfig } from "#app";
```

**Comment by johannschopplich** [comment]
Oh snap. 🙈 Thanks for reporting!

**Comment by johannschopplich** [comment]
That's the same problem. Somehow didn't happen during playground testing...

**Comment by johannschopplich** [comment]
Fixed in https://github.com/johannschopplich/nuxt-gtag/commit/e09a1e597d7ca2dfb42906bd4c7358fa64f92afb.

Please use v0.2.2 – should be deployed in a minute. 🙂
