### ISSUE TITLE
Update documentation on nuxt.com/modules/gtag

### ISSUE THREAD

**Issue by ShreyanshJF** [johannschopplich/nuxt-gtag#52]
The documentation on [nuxt.com/modules/gtag](https://nuxt.com/modules/gtag) outdated
I don't know if this is under your control but thought I'd put it down as an issue.

**Comment by johannschopplich** [comment]
Thanks for letting me know! I just checked – the documentation is up to date. The Nuxt modules repo fetched the README at built time, so it will always be up to date.
