### ISSUE TITLE
Uncaught TypeError: gtag is not a function

### ISSUE THREAD

**Issue by bmhtech07** [johannschopplich/nuxt-gtag#53]
### Environment

- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      runtimeConfig, app, modules, devtools, imports, css, postcss, auth, gtag, routeRules, build
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0-beta.4, nuxt-gtag@2.0.4
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-j7dume?file=app.vue

### Describe the bug

The module works with normal tracking events, but calling `gtag()` from `const { gtag } = useGtag()` returns 'Uncaught TypeError: gtag is not a function'

### Additional context

I had a brief poke around in the module's composables, but can't see anything obvious...

### Logs

```shell-script
Uncaught TypeError: gtag is not a function
```

**Comment by johannschopplich** [comment]
Thanks for the reproduction! So many people don't create one. 🙂 

You have to call the composable to destructure assignment:

```diff
-const { gtag } = useGtag
+const { gtag } = useGtag()
```

Calling `useGtag()` will provide you all of the methods, like `gtag`.

**Comment by bmhtech07** [comment]
Hahaha, no way!

I actually checked this multiple times... do dumb... sorry to waste time 🤦‍♂️

**Comment by johannschopplich** [comment]
No problem! Happens to all of us.

**Comment by bmhtech07** [comment]
Ah... hold up. I am getting that error still in local dev. Will do some further digging as to why...

**Comment by RomanSkrypnik** [comment]
@bmhtech07, @johannschopplich, any updates?
Facing this issue inside my nuxt module which I installed as npm package:
![image](https://github.com/johannschopplich/nuxt-gtag/assets/44501848/97a77168-beb6-4216-98d8-498969f50296)
![image](https://github.com/johannschopplich/nuxt-gtag/assets/44501848/41d8306b-d1d5-4311-8362-e3d2fd73c7b5)
Module playground works fine

**Comment by bmhtech07** [comment]
Yes! It was due to Nuxt version. Make sure you're on 3.8 or above...

**Comment by RomanSkrypnik** [comment]
@bmhtech07, thanks for the answer!
Seems my problem doesn't relate to this one
In my case, `useGtag` doesn't return object - it returns gtag function:
![image](https://github.com/johannschopplich/nuxt-gtag/assets/44501848/73515a75-244a-450b-80ab-d62d2119eaec)
![image](https://github.com/johannschopplich/nuxt-gtag/assets/44501848/ee6e8aee-eee7-4b58-b215-1c3ffec2400d)

**Comment by johannschopplich** [comment]
Please open a separate issue with a dedicated reproduction. Thanks in advance!
