### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'is_legacy_loaded')

### ISSUE THREAD

**Issue by agracia-foticos** [johannschopplich/nuxt-gtag#55]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.1`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

When i load the module we have this errors:
![image](https://github.com/johannschopplich/nuxt-gtag/assets/77386602/ddf7f6b6-b9f6-4e2c-a543-813aed122e74)

### Describe the bug

When i load the module we have this errors:
![image](https://github.com/johannschopplich/nuxt-gtag/assets/77386602/ddf7f6b6-b9f6-4e2c-a543-813aed122e74)

**Comment by johannschopplich** [comment]
Thanks for the report. Can you please provide a reproducible example? Please use a template below to create a minimal reproduction:
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

Thanks in advance!

**Comment by gorkie** [comment]
The same happens to me. It seems when i use to multiple tags in nuxt.config.

**Comment by nasdaq-dubai-dfm** [comment]
> The same happens to me. It seems when i use to multiple tags in nuxt.config.

Exactly the same issue. Only when using multiple tags.

**Comment by muhammedjenos** [comment]
> The same happens to me. It seems when i use to multiple tags in nuxt.config.

Exactly the same issue. Only when using multiple tags. Just IDs inside tags array. :(

**Comment by johannschopplich** [comment]
I have to close this issue based on:
- @agracia-foticos It appears from the screenshot provided that you're using a the Google Tag Manager, not a Google Tag ID. The error occurs in the Google GTM, not this Nuxt module. 
- @gorkie @muhammedjenos  No reproduction has been provided. Please use the Nuxt starters provided above to create a reproduction and then open a new issue. Thanks!

**Comment by johannschopplich** [comment]
@gorkie @muhammedjenos This has been fixed in the latest version v2.0.6. Please upgrade.
