### ISSUE TITLE
Using partytown to run this in worker thread

### ISSUE THREAD

**Issue by husayt** [johannschopplich/nuxt-gtag#70]
### Describe the feature

Is using partytown integration could imporve performance: https://github.com/nuxt-modules/partytown

Google analytics is one of the of example usecases in the provided repo.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
Absolutely, but Partytown is a whole other solution to provide third-party script support. Both modules serve a different purpose.

**Comment by husayt** [comment]
Thank you for your reply. I also noted similar question and it seems, for partytown it is recommended to use g-tag script directly

https://github.com/johannschopplich/nuxt-gtag/discussions/25
