### ISSUE TITLE
Enhance doc : Enhanced measurement according to new ux on google analytics side.

### ISSUE THREAD

**Issue by lesmoutonssauvages** [johannschopplich/nuxt-gtag#71]
### Describe the feature

In the readme we should add a 5 th point.

After: 4. Next, toggle the switch button near “Enhanced measurement”.
add: 
**5. Open "advanced parameters" and ensure "on page change based on history" is checked**

Hope this help

<img width="604" alt="Capture d’écran 2024-05-19 à 08 22 56" src="https://github.com/johannschopplich/nuxt-gtag/assets/40919200/fe785f1a-33b1-4c0b-a7bf-d6c6fc771545">

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
Good idea! PR welcome 🙌
