### ISSUE TITLE
Compatibility issue with Nuxt < 3.7

### ISSUE THREAD

**Issue by drusellers** [johannschopplich/nuxt-gtag#73]
### Environment

npx nuxi info
Working directory: /Users/drusellers/dev/vc/endless-aisle/src/Display                                                                                                    7:56:59 AM
Nuxt project info: (copied to clipboard)                                                                                                                                 7:56:59 AM

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.4.2
- CLI Version:      3.11.1
- Nitro Version:    2.3.3
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      runtimeConfig, experimental, app, image, modules, build, css, gtag
- Runtime Modules:  @nuxt/image@1.7.0, nuxt-gtag@2.0.6
- Build Modules:    -
------------------------------

### Reproduction

```sh
npx nuxi upgrade --force
ℹ Package manager: npm 10.2.3                                                                                                                                           8:01:29 AM
ℹ Current Nuxt version: 3.4.2                                                                                                                                           8:01:29 AM
ℹ Recreating node_modules and package-lock.json. If you encounter any issues, revert the changes and try with --no-force                                                8:01:29 AM
ℹ Installing latest Nuxt 3 release...                                                                                                                                   8:01:39 AM
...
ℹ Cleaning up generated Nuxt files and caches...                                                                                                                        8:02:45 AM
ℹ Upgraded Nuxt version: 3.4.2                                                                                                                                          8:02:45 AM
✔ You're already using the latest version of Nuxt.
```

```sh
npm ls
Display@ /Users/drusellers/dev/vc/endless-aisle/src/Display
...
├── @nuxt/image@1.7.0
├── @nuxtjs/eslint-config-typescript@12.1.0
...
├── nuxt-gtag@2.0.6
├── nuxt@3.11.2
...
├── vue@3.4.27
...
```

```sh
Nuxt 3.11.2 with Nitro 2.9.6                                                                                                                                             8:06:02 AM
                                                                                                                                                                         8:06:02 AM
  ➜ Local:    http://localhost:3001/
  ➜ Network:  use --host to expose


 WARN  Module nuxt-gtag is disabled due to incompatibility issues:                                                                                                       8:06:03 AM
 - [nuxt] Nuxt version ^3.7 is required but currently using 3.4.2
```

### Describe the bug

Package doesn't seem to work with the latest version of nuxt.

### Additional context

I've tried all the upgrade commands I can find, but you may know of some secret I do not. :(

**Comment by johannschopplich** [comment]
Seems like you still run Nuxt v3.4.2. Unfortunately, this isn't an issue of this module.

Please delete all of your `node_modules` folders with `npx npkill` and check if Nuxt is updated in your `package.json` file. Thanks!
