### ISSUE TITLE
Configure how `useTrackEvent()` and `gtag()` push data to data layer

### ISSUE THREAD

**Issue by bjarnef** [johannschopplich/nuxt-gtag#79]
### Describe the feature

When using `useTrackEvent()` or `gtag()` it push the following object to data layer.
Not sure the reason behind this, but is it possible to configure?

So instead of this:

```
{
   "0": "event",
   "1": "show_contact_info",
   "2": {
      "email": "mail@mail.dk",
      "phone": "12 34 56 78"
   }
}
```

the this format:

```
{
   "event": "show_contact_info",
   "email": "mail@mail.dk",
   "phone": "12 34 56 78"
}
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
Hi there, I'm not sure, what you mean. The `gtag` function exposed by `useGtag` accepts the same arguments as the `gtag` global function from the official Google Tag library. So you can use this (if you're using TypeScript, you will even get type completion for the available params):

```ts
gtag('event', 'show_contact_info', {
  email: 'mail@mail.dk',
  phone: '12 34 56 78',
})
```

**Comment by bjarnef** [comment]
Hi @johannschopplich

I tried both approaches, but in both cases `dataLayer` checker shows the following.

![image](https://github.com/johannschopplich/nuxt-gtag/assets/2919859/c7202e0e-716c-4315-ac5f-b267acccd469)

comparing to e.g Sleeknote or similar and traditional push to data layer in JS:

```
window.dataLayer = window.dataLayer || [];

window.dataLayer.push(obj);
```

![image](https://github.com/johannschopplich/nuxt-gtag/assets/2919859/82eea0b0-093c-4cab-b6ab-6605910283ea)

**Comment by bjarnef** [comment]
3 examples:

```
declare global {
    interface Window { dataLayer: any; }
}

window.dataLayer = window.dataLayer || [];

const onContactClick = () => {

  const contactPerson = {
    email: "mail@mail.dk",
    phone: "12 34 56 78"
  };

  const { gtag } = useGtag();

  gtag('event', 'show_contact_info', contactPerson)

  useTrackEvent('show_contact_info', contactPerson)

  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push({
    event: 'show_contact_info',
    contactPerson
  });

}
```

**gtag()**
![image](https://github.com/johannschopplich/nuxt-gtag/assets/2919859/b8bbbc06-4bee-4d89-8b74-b5b278f41f76)

**useTrackEvent()**

![image](https://github.com/johannschopplich/nuxt-gtag/assets/2919859/26893928-0914-47fe-93da-9f71458e4154)

**window.dataLayer**

![image](https://github.com/johannschopplich/nuxt-gtag/assets/2919859/24b595d4-1b1e-4a8b-bd80-11884cfb0030)

**Comment by johannschopplich** [comment]
OK, but that seems to be a different approach. We use this to push the event args directly to the `gtag` function from Google.

https://github.com/johannschopplich/nuxt-gtag/blob/faeaf1ed1dbcdd63d7c9c994d45705049e7578e7/src/runtime/composables/useTrackEvent.ts#L8

Pushing to `window.dataLayer` results in a different behaviour, because the official `gtag` functions pushes the `arguments` list of the input params, not a plain object:
```ts
// Taken from official Google Tag snippet
function gtag(){dataLayer.push(arguments);}
```

You could write your own wrapper to handle data pushing, but for the library, I think sticking to the official implementation is best.

**Comment by bjarnef** [comment]
Okay, maybe it has change a bit since as this claims that there is no difference between `gtag()` and `dataLayer.push()`:
https://stackoverflow.com/a/69916520
