### ISSUE TITLE
Warning 'Third-party cookie will be blocked in future Chrome versions...' after installing nuxt-gtag

### ISSUE THREAD

**Issue by Pawel2505** [johannschopplich/nuxt-gtag#81]
### Environment

Operating System: Windows_NT
Node Version:     v18.12.1
Nuxt Version:     3.11.2
CLI Version:      3.11.1
Nitro Version:    2.9.6
Browser: Chrome Version 126.0.6478.127

### Reproduction

I set up nuxt-gtag in my app with the basic configuration i.e. gtag: { id: 'my_id', }, 

### Describe the bug

After running my Nuxt App locally I get the following warning in Chrome console:

>  'Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox'

**Comment by johannschopplich** [comment]
This originates in the official `gtag.js` from Google that will be injected on the page, not this module.
