### ISSUE TITLE
initCommands has a default value of [], but requires declaration

### ISSUE THREAD

**Issue by OllyNicholass** [johannschopplich/nuxt-gtag#92]
Should the `initCommands` property within the ModuleOptions be optional?

The documentation doesn't allude to requiring it to be set, and it has a default value of an empty array.

https://github.com/johannschopplich/nuxt-gtag/blob/e7282b5f0c3dea1635122838ec2305bf77400102/src/module.ts#L51C1-L51C49

**Comment by johannschopplich** [comment]
PR welcome!
